######################################################################
# Automatically generated by qmake (3.0) ?? 12? 14 16:56:43 2014
######################################################################

TEMPLATE = app
TARGET = qt-test.cgi
INCLUDEPATH += .

# Input
SOURCES += main.cpp

QT += network
CONFIG += C++11
